[package]
name = "controlgrama"
version = "1.0.0"
description = "ControlGrama"
authors = ["ControlGrama"]
edition = "2021"

[lib]
name = "controlgrama_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
