/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiariasRouteImport } from './routes/diarias'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as OsRouteImport } from './routes/os'
import { Route as PontoRouteImport } from './routes/ponto'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as EquipeWorkerIdRouteImport } from './routes/equipe.$workerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariasRoute = DiariasRouteImport.update({
  id: '/diarias',
  path: '/diarias',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeWorkerIdRoute = EquipeWorkerIdRouteImport.update({
  id: '/$workerId',
  path: '/$workerId',
  getParentRoute: () => EquipeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diarias': typeof DiariasRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/os': typeof OsRoute
  '/ponto': typeof PontoRoute
  '/relatorios': typeof RelatoriosRoute
  '/equipe/$workerId': typeof EquipeWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diarias': typeof DiariasRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/os': typeof OsRoute
  '/ponto': typeof PontoRoute
  '/relatorios': typeof RelatoriosRoute
  '/equipe/$workerId': typeof EquipeWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diarias': typeof DiariasRoute
  '/equipe': typeof EquipeRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/os': typeof OsRoute
  '/ponto': typeof PontoRoute
  '/relatorios': typeof RelatoriosRoute
  '/equipe/$workerId': typeof EquipeWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diarias'
    | '/equipe'
    | '/financeiro'
    | '/os'
    | '/ponto'
    | '/relatorios'
    | '/equipe/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diarias'
    | '/equipe'
    | '/financeiro'
    | '/os'
    | '/ponto'
    | '/relatorios'
    | '/equipe/$workerId'
  id:
    | '__root__'
    | '/'
    | '/diarias'
    | '/equipe'
    | '/financeiro'
    | '/os'
    | '/ponto'
    | '/relatorios'
    | '/equipe/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiariasRoute: typeof DiariasRoute
  EquipeRoute: typeof EquipeRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  OsRoute: typeof OsRoute
  PontoRoute: typeof PontoRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diarias': {
      id: '/diarias'
      path: '/diarias'
      fullPath: '/diarias'
      preLoaderRoute: typeof DiariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$workerId': {
      id: '/equipe/$workerId'
      path: '/$workerId'
      fullPath: '/equipe/$workerId'
      preLoaderRoute: typeof EquipeWorkerIdRouteImport
      parentRoute: typeof EquipeRoute
    }
  }
}

interface EquipeRouteChildren {
  EquipeWorkerIdRoute: typeof EquipeWorkerIdRoute
}

const EquipeRouteChildren: EquipeRouteChildren = {
  EquipeWorkerIdRoute: EquipeWorkerIdRoute,
}

const EquipeRouteWithChildren =
  EquipeRoute._addFileChildren(EquipeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiariasRoute: DiariasRoute,
  EquipeRoute: EquipeRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  OsRoute: OsRoute,
  PontoRoute: PontoRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
