/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiariasRouteImport } from './routes/diarias'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as PontoRouteImport } from './routes/ponto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariasRoute = DiariasRouteImport.update({
  id: '/diarias',
  path: '/diarias',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diarias': typeof DiariasRoute
  '/financeiro': typeof FinanceiroRoute
  '/ponto': typeof PontoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diarias': typeof DiariasRoute
  '/financeiro': typeof FinanceiroRoute
  '/ponto': typeof PontoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diarias': typeof DiariasRoute
  '/financeiro': typeof FinanceiroRoute
  '/ponto': typeof PontoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diarias' | '/financeiro' | '/ponto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diarias' | '/financeiro' | '/ponto'
  id: '__root__' | '/' | '/diarias' | '/financeiro' | '/ponto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiariasRoute: typeof DiariasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  PontoRoute: typeof PontoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diarias': {
      id: '/diarias'
      path: '/diarias'
      fullPath: '/diarias'
      preLoaderRoute: typeof DiariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiariasRoute: DiariasRoute,
  FinanceiroRoute: FinanceiroRoute,
  PontoRoute: PontoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
